require.config({
    baseUrl:'/pubilc/assets',
    paths:{
        jquery:'/pubilc/assets/jquery/jquery',
        cookie:'/pubilc/assets/jquery-cookie/jquery.cookie',
        template:'/pubilc/assets/artTemplate/template-web',
        common:'../js/common',
        login:'../js/login',
        teacherlist:'../js/teacherlist'
    }
});